package com.dhu.gene;

public class SysCodeKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code.code
     *
     * @mbg.generated Mon Oct 03 22:16:53 CST 2016
     */
    private String code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_code.type
     *
     * @mbg.generated Mon Oct 03 22:16:53 CST 2016
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code.code
     *
     * @return the value of t_sys_code.code
     *
     * @mbg.generated Mon Oct 03 22:16:53 CST 2016
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code.code
     *
     * @param code the value for t_sys_code.code
     *
     * @mbg.generated Mon Oct 03 22:16:53 CST 2016
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_code.type
     *
     * @return the value of t_sys_code.type
     *
     * @mbg.generated Mon Oct 03 22:16:53 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_code.type
     *
     * @param type the value for t_sys_code.type
     *
     * @mbg.generated Mon Oct 03 22:16:53 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }
}