package com.dhu.gene;

import com.dhu.gene.SysCode;
import com.dhu.gene.SysCodeExample;
import com.dhu.gene.SysCodeKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_code
     *
     * @mbg.generated Mon Oct 03 22:16:53 CST 2016
     */
    long countByExample(SysCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_code
     *
     * @mbg.generated Mon Oct 03 22:16:53 CST 2016
     */
    int deleteByExample(SysCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_code
     *
     * @mbg.generated Mon Oct 03 22:16:53 CST 2016
     */
    int deleteByPrimaryKey(SysCodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_code
     *
     * @mbg.generated Mon Oct 03 22:16:53 CST 2016
     */
    int insert(SysCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_code
     *
     * @mbg.generated Mon Oct 03 22:16:53 CST 2016
     */
    int insertSelective(SysCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_code
     *
     * @mbg.generated Mon Oct 03 22:16:53 CST 2016
     */
    List<SysCode> selectByExample(SysCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_code
     *
     * @mbg.generated Mon Oct 03 22:16:53 CST 2016
     */
    SysCode selectByPrimaryKey(SysCodeKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_code
     *
     * @mbg.generated Mon Oct 03 22:16:53 CST 2016
     */
    int updateByExampleSelective(@Param("record") SysCode record, @Param("example") SysCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_code
     *
     * @mbg.generated Mon Oct 03 22:16:53 CST 2016
     */
    int updateByExample(@Param("record") SysCode record, @Param("example") SysCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_code
     *
     * @mbg.generated Mon Oct 03 22:16:53 CST 2016
     */
    int updateByPrimaryKeySelective(SysCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_code
     *
     * @mbg.generated Mon Oct 03 22:16:53 CST 2016
     */
    int updateByPrimaryKey(SysCode record);
}